spring:
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: "5"
            client-secret: "G"
            scope: profile, email
            redirect-uri: '{baseUrl}/login/oauth2/code/{registrationId}'
            client-authentication-method: client_secret_post
          naver:
            client-id: "Z"
            client-secret: "l"
            client-name: Naver
            authorization-grant-type: authorization_code
            redirect-uri: '{baseUrl}/login/oauth2/code/{registrationId}'
            scope: name, email, profile_image
        provider:
          naver:
            authorization-uri: https://nid.naver.com/oauth2.0/authorize
            token-uri: https://nid.naver.com/oauth2.0/token
            user-info-uri: https://openapi.naver.com/v1/nid/me
            user-name-attribute: response

